In [1]:
#Numpy Basic Operations.

In [3]:
#Creating Arrays
import numpy as np
arr = np.array([1, 2, 3])
arr

array([1, 2, 3])

In [4]:
#Using built-in functions:

zeros_array = np.zeros((2, 3))
ones_array = np.ones((2, 3))
empty_array = np.empty((2, 3))
full_array = np.full((2, 3), 7)
eye_array = np.eye(3)  # Identity matrix

In [5]:
zeros_array

array([[0., 0., 0.],
       [0., 0., 0.]])

In [6]:
ones_array

array([[1., 1., 1.],
       [1., 1., 1.]])

In [7]:
empty_array

array([[0., 0., 0.],
       [0., 0., 0.]])

In [8]:
full_array

array([[7, 7, 7],
       [7, 7, 7]])

In [9]:
eye_array

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [10]:
#Shape and size:
arr.shape  # (rows, columns)
arr.size   # Total number of elements
arr.ndim   # Number of dimensions

1

In [11]:
arr.shape  # (rows, columns)

(3,)

In [12]:
arr.size   # Total number of elements

3

In [13]:
arr.ndim   # Number of dimensions

1

In [14]:
arr=np.array([2,3,4,5,6,7,8])

In [15]:
arr

array([2, 3, 4, 5, 6, 7, 8])

In [16]:
arr.shape

(7,)

In [17]:
arr.size

7

In [25]:
#Array Indexing and Slicing

In [26]:
arr[0]  # First element

2

In [27]:
arr[-1] # Last element

8

In [28]:
#Slicing:

In [29]:
arr[1:3]  # Elements from index 1 to 2

array([3, 4])

In [30]:
arr[:2]   # First two elements

array([2, 3])

In [31]:
arr[::2]  # Every other element

array([2, 4, 6, 8])

In [32]:
#Multi-dimensional arrays:

In [ ]:
#Arithmetic Operations

In [41]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = a + b
d = a * b
e = a - b
f = a/b

In [38]:
c

array([5, 7, 9])

In [39]:
d

array([ 4, 10, 18])

In [42]:
e

array([-3, -3, -3])

In [43]:
f

array([0.25, 0.4 , 0.5 ])

In [ ]:
#Broadcasting

In [48]:
arr = np.array([1, 2, 3])
b = 2
c = arr * b  # Array [1, 2, 3] is multiplied by 2

In [49]:
c

array([2, 4, 6])

In [ ]:
#Mathematical Functions

In [51]:
arr = np.array([1, 2, 3])
b = 2

In [57]:
'''np.add(a, b)
np.subtract(a, b)
np.multiply(a, b)
np.divide(a, b)
np.power(a, 2)'''

'np.add(a, b)\nnp.subtract(a, b)\nnp.multiply(a, b)\nnp.divide(a, b)\nnp.power(a, 2)'

In [52]:
np.add(a, b)

array([3, 4, 5])

In [53]:
np.subtract(a, b)

array([-1,  0,  1])

In [54]:
np.multiply(a, b)

array([2, 4, 6])

In [55]:
np.divide(a, b)

array([0.5, 1. , 1.5])

In [56]:
np.power(a, 2)

array([1, 4, 9])

In [18]:
arr.itemsize

8

In [19]:
arr.dtype

dtype('int64')

In [20]:
arr[3:1]

array([], dtype=int64)

In [21]:
arr[1:3]

array([3, 4])

In [22]:
arr[::-1]

array([8, 7, 6, 5, 4, 3, 2])

In [23]:
arr[::-3]

array([8, 5, 2])

In [24]:
arr[2:10:-1]

array([], dtype=int64)

In [ ]:
arr = np.array([1, 2, 3])
b = 2

In [59]:
#Mathematical Functions
#Universal functions (ufuncs):
#np.add(a, b)
#np.subtract(a, b)
#np.multiply(a, b)
#np.divide(a, b)
#np.power(a, 2)

In [60]:
np.add(a,b)

array([3, 4, 5])

In [61]:
np.subtract(a,b)

array([-1,  0,  1])

In [63]:
np.multiply(a,b)

array([2, 4, 6])

In [65]:
np.divide(a,b)

array([0.5, 1. , 1.5])

In [66]:
np.power(a,b)

array([1, 4, 9])

In [67]:
#Statistical functions:
#np.mean(arr)
#np.median(arr)
#np.std(arr)
#np.var(arr)

In [72]:
arr = np.array([1, 2, 3])

In [73]:
np.mean(arr)

2.0

In [74]:
np.median(arr)

2.0

In [75]:
np.std(arr)

0.816496580927726

In [77]:
np.var(arr)

0.6666666666666666

In [78]:
#Trigonometric functions

In [79]:
#np.sin(arr)
#np.cos(arr)
#np.tan(arr)

In [80]:
np.sin(arr)


array([0.84147098, 0.90929743, 0.14112001])

In [81]:
np.cos(arr)

array([ 0.54030231, -0.41614684, -0.9899925 ])

In [82]:
np.tan(arr)

array([ 1.55740772, -2.18503986, -0.14254654])

In [83]:
#Matrix Operations

In [84]:
#Dot product:
np.dot(a,b)

array([2, 4, 6])

In [85]:
arr = np.array([1, 2, 3])
b = 2

In [88]:
#Matrix multiplication:
a = np.array([1, 2, 3])  # 1-dimensional array
b = np.array([4, 5, 6])  # 1-dimensional array
np.matmul(a,b)

32

In [90]:
#Transpose
arr = np.array([1, 2, 3])

In [91]:
a.T

array([1, 2, 3])

In [92]:
arr = np.array([1, 2, 3])
transposed_arr = arr.T

print("Original array:", arr)
print("Transposed array:", transposed_arr)

Original array: [1 2 3]
Transposed array: [1 2 3]


In [93]:
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
transposed_arr_2d = arr_2d.T

print("Original 2D array:\n", arr_2d)
print("Transposed 2D array:\n", transposed_arr_2d)

Original 2D array:
 [[1 2 3]
 [4 5 6]]
Transposed 2D array:
 [[1 4]
 [2 5]
 [3 6]]


In [94]:
arr = np.array([1, 2, 3])
column_vector = arr.reshape(-1, 1)
row_vector = column_vector.T

print("Column vector:\n", column_vector)
print("Row vector:\n", row_vector)

Column vector:
 [[1]
 [2]
 [3]]
Row vector:
 [[1 2 3]]


In [95]:
#Solving Linear Systems
#Solving Ax = b:

In [96]:
A = np.array([[3, 1], [1, 2]])
b = np.array([9, 8])
x = np.linalg.solve(A, b)

In [97]:
#Eigenvalues and eigenvectors:

In [98]:
eigvals, eigvecs = np.linalg.eig(A)

In [99]:
eigvals

array([3.61803399, 1.38196601])

In [100]:
eigvecs

array([[ 0.85065081, -0.52573111],
       [ 0.52573111,  0.85065081]])

In [102]:
np.random.rand(3, 2)   # Uniform distribution over [0, 1)

array([[0.5862952 , 0.39702381],
       [0.59003947, 0.69346879],
       [0.31356762, 0.94400065]])

In [103]:
np.random.randn(3, 2)  # Standard normal distribution

array([[-1.17742249, -0.10030975],
       [-0.10036511,  1.01601434],
       [-0.57772788,  0.38972737]])

In [104]:
#Random integers:
np.random.randint(0, 10, (3, 3))

array([[7, 6, 4],
       [2, 6, 6],
       [6, 6, 9]])

In [105]:
#Random choice:
np.random.choice([1,2,3,4,5],size=3)

array([5, 2, 4])

In [109]:
# Set the seed
np.random.seed(42)

# Generate random numbers
random_numbers = np.random.rand(5)
print(random_numbers) #Output (will always be the same for seed 42):

[0.37454012 0.95071431 0.73199394 0.59865848 0.15601864]


In [111]:
# Without setting a seed
random_numbers = np.random.rand(5)
print(random_numbers) #Output (will vary each time you run the code):

[0.02058449 0.96990985 0.83244264 0.21233911 0.18182497]


In [114]:
#Reproducibility in Functions
def generate_random_numbers(seed, size):
    np.random.seed(seed)
    return np.random.rand(size)

print(generate_random_numbers(42, 5))
print(generate_random_numbers(24, 5))

[0.37454012 0.95071431 0.73199394 0.59865848 0.15601864]
[0.9600173  0.69951205 0.99986729 0.2200673  0.36105635]


In [115]:
#2d Array

In [116]:
a = np.array([[2,3],[4,5],[6,7]])

In [117]:
a

array([[2, 3],
       [4, 5],
       [6, 7]])

In [118]:
a.shape

(3, 2)

In [119]:
a.ndim

2

In [120]:
a.dtype

dtype('int64')

In [121]:
a.itemsize

8

In [122]:
a.size

6

In [123]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [127]:
np.full((3,3),10)

array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

In [128]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [130]:
np.arange(1,21)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [132]:
a=np.arange(1,21,3)

In [133]:
a.dtype

dtype('int64')

In [136]:
a=np.arange(1,21,3,dtype=float)

In [137]:
a.dtype

dtype('float64')

In [139]:
a =np.array([[3,4],[5,6],[7,8]])
a

array([[3, 4],
       [5, 6],
       [7, 8]])

In [140]:
a.reshape(2,3)

array([[3, 4, 5],
       [6, 7, 8]])

In [141]:
a.reshape(6,1)

array([[3],
       [4],
       [5],
       [6],
       [7],
       [8]])

In [143]:
a.reshape(1,6)

array([[3, 4, 5, 6, 7, 8]])

In [144]:
a

array([[3, 4],
       [5, 6],
       [7, 8]])